<?php
	require "functions.php";
	$ajax = new Stratek();
	 if(isset($_POST['edit'])){
        //edit user details
        $ajax->verifyData($_POST['pid'],$_POST['table']);
    }elseif(isset($_POST['updateStatusPid'])){
    	$ajax->updateStatusAdminPid($_POST['pid'],$_POST['table']);
    }elseif(isset($_POST['deleteReq'])){
    	$ajax->deleteReqAdmin($_POST['pid'],$_POST['table']);
    }elseif(isset($_POST['unlock'])){
        $ajax->unlockSession($_POST['unlock']);
    }elseif(isset($_POST['lock'])){
        $ajax->lockSession();
    }elseif(isset($_POST['loadBillingParamsCategory'])){
        $ajax->loadBillingParamsCategory($_POST['loadBillingParamsCategory']);
    }elseif(isset($_POST['newOrder'])){
        $ajax->addOrder();
    }elseif(isset($_POST['updateOrder'])){
        $ajax->updateOrder();
    }elseif(isset($_POST['loadCurrentOrders'])){
        $ajax->loadCurrentOrders();
    }elseif(isset($_POST['previewExistingOrders'])){
        $ajax->previewExistingOrders();
    }elseif(isset($_POST['removeExistingOrder'])){
        $ajax->removeExistingOrder($_POST['tid']);
    }elseif(isset($_POST['addExistingOrder'])){
        $ajax->addExistingOrder($_POST['tid']);
    }elseif(isset($_POST['deleteExistingOrder'])){
        $ajax->deleteExistingOrder();
    }elseif(isset($_POST['verifyExistingOrder'])){
        $ajax->verifyExistingOrder();
    }elseif(isset($_POST['editExistingOrder'])){
        $ajax->editExistingOrder();
    }elseif(isset($_POST['processBill'])){
        $ajax->billProcess();
    }elseif(isset($_POST['processOrder'])){
        $ajax->processOrder();
    }elseif(isset($_POST['setDiscount'])){
        $ajax->setDiscount($_POST['setDiscount']);
    }elseif(isset($_POST['completeProcessBill'])){
        $ajax->completeProcessBill();
    }elseif(isset($_POST['previewSplitBill'])){
        $ajax->previewSplitBill();
    }elseif(isset($_POST['splitTid'])){
        $ajax->setSplitTid();
    }elseif(isset($_POST['moveSplitItem'])){
        $ajax->moveSplitItem();
    }elseif(isset($_POST['saveSplitBillProcess'])){
        $ajax->saveSplitBillProcess();
    }elseif(isset($_POST['previewMergeBill'])){
        $ajax->previewMergeBill();
    }elseif(isset($_POST['mergeBill'])){
        $ajax->mergeBill();
    }elseif(isset($_POST['mergeMoveAll'])){
        $ajax->moveAllMerge();
    }elseif(isset($_POST['saveMergeBill'])){
        $ajax->saveMergeBill();
    }elseif(isset($_POST['updateExistingOrder'])){
        $ajax->updateExistingOrder();
    }elseif(isset($_POST['addExistingOrder1'])){
        $ajax->addExistingOrder1();
    }elseif(isset($_POST['addExistingOrder2'])){
        $ajax->addExistingOrder2();
    }elseif(isset($_POST['removeExistingOrder1'])){
        $ajax->removeExistingOrder1();
    }elseif(isset($_POST['removeExistingOrder2'])){
        $ajax->removeExistingOrder2();
    }elseif(isset($_POST['mergeSelectedBill'])){
        $ajax->mergeSelectedBill();
    }elseif(isset($_POST['printDocument'])){
        $ajax->printDocument($_POST['printDocument']);
    }elseif(isset($_POST['previewProcessedBill'])){
        $ajax->previewProcessedBill();
    }elseif(isset($_POST['deleteProcessedBill'])){
        $ajax->deleteProcessedBill($_POST['deleteProcessedBill']);
    }elseif(isset($_POST['editProcessedBill'])){
        $ajax->editProcessedBill();
    }elseif(isset($_POST['setProcessedBillTid'])){
        $ajax->setProcessedBillTid($_POST['setProcessedBillTid']);
    }elseif(isset($_POST['completeProcessedBill'])){
        $ajax->completeProcessedBill();
    }elseif(isset($_POST['setVTable'])){
        $ajax->setVTable();
    }
?>